name: BIRSBiointegration
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - umap-learn
  - scikit-learn
  - pandas
  - pathlib
  - numpy
  - seaborn
  - python=3.7
  - scipy
  - matplotlib
  - dask
  - hdbscan
  - scanpy
  - ipykernel
  - qtconsole
